import React from 'react'
import axios from 'axios';
import useSWR from 'swr';
import { useRouter } from 'next/router';
import Link from 'next/link';
import Head from 'next/head';
import Layout from '@/components/common/Layout';

const fetcher = (url) => axios.get(url, { headers: { token: localStorage.getItem('lr-admin-token') } }).then(res => res.data);

export default function Index() {
    const router = useRouter()
    const { Id } = router.query
    const { data, error } = useSWR(`${process.env.NEXT_PUBLIC_URL}admin/view-sell-data/${Id}`, fetcher);

    if (error) return 'Opps something went wrong.'
    if (!data) return 'Please wait ...'

    const updateSellOrderStateAdmin = async (e) => {
        e.preventDefault();
        const formData = new FormData(document.getElementById('admin-sell-request-order-form'));

        await axios.post(`${process.env.NEXT_PUBLIC_URL}admin/admin-sell-request-status-update`, formData, {
            headers: {
                'Content-Type': 'application/json',
                'token': localStorage.getItem('lr-admin-token'),
            }
        }).then((res) => {
            if (res && res.data && res.data.status === 1) {
                alert(res && res.data && res.data.message);
                router.push('/admin/sell-data')
            }
        }).catch((e) => {
            if (e && e.message) {
                alert(e.message);
            } else if (e && e.response && e.response.data && e.response.data.status === 0) {
                alert(e.response.data.message);
            }
        })
    }


    return (
        <>
            <Head>
                <title>LR | Sell Data Detail</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="img/favicon.ico" />
            </Head>
            <Layout>
                <div className="wrapper">
                    <div className="detail-list" >

                        <h4>Sell Request Details</h4>

                        <p>Order id: <span>{data.data.request_id}</span></p>

                        <div className="detail-main">

                            <div className="detail-row box">
                                <h5>Car Detail</h5>
                                <table>
                                    <tr>
                                        <th>Brand Name</th>
                                        <td>
                                            <span>{data.data && data.data.brand_name}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Model Name</th>
                                        <td>
                                            <span>{data.data && data.data.model_name}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Variant Name</th>
                                        <td>
                                            <span>{data.data && data.data.variant_name}</span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>Year</th>
                                        <td>
                                            <span>{data.data.year}</span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>State</th>
                                        <td>
                                            <span>{data.data.state}</span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>KMS</th>
                                        <td>
                                            <span>{data.data.kms && Number(data.data.kms).toLocaleString('en-US')}</span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>Ownership</th>
                                        <td>
                                            <span>{data.data.ownership}{data.data.ownership === '1' ? 'st' : data.data.ownership === '2' ? 'nd' : data.data.ownership === '3' ? 'rd' : ''}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Car Insurance</th>
                                        <td>
                                            <span>
                                                {data.data.car_insurance ? <Link target='_blank' href={`${process.env.NEXT_PUBLIC_URL}${data.data.car_insurance}`}>
                                                    View
                                                </Link> : '-'
                                                }


                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>RC Registration Certificate</th>
                                        <td>
                                            <span>
                                                {data.data.rc_registration_certificate ? <Link target='_blank' href={`${process.env.NEXT_PUBLIC_URL}${data.data.rc_registration_certificate}`}>
                                                    View
                                                </Link> : '-'}

                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Location</th>
                                        <td>
                                            <span>{data.data.full_address}</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Expected Price</th>
                                        <td>
                                            <span>{data.data.expected_sell_price ? data.data.expected_sell_price : '-'}</span>
                                        </td>
                                    </tr>
                                </table>

                            </div>

                            <div className="detail-row box">
                                <h5>User Details</h5>

                                <table>

                                    <tr>
                                        <th>User Name</th>
                                        <td>
                                            <span>{data.data && data.data.user_name ? data.data.user_name : '-'}</span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>User Contact</th>
                                        <td>
                                            <span>{data.data.user_mobile}</span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>User Email</th>
                                        <td>
                                            <span>{data.data.user_email ? data.data.user_email : '-'}</span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>User Address Type</th>
                                        <td>
                                            <span>{data.data && data.data.address_type ? data.data.address_type : '-'}</span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>User Address </th>
                                        <td>
                                            <span>{data.data && data.data.full_address ? data.data.full_address : '-'}</span>
                                        </td>
                                    </tr>
                                </table>

                            </div>

                            <div className="detail-row box">

                                <h5>Evaluation Schedule Detail</h5>

                                <table>

                                    <tr>
                                        <th>Date</th>
                                        <td>
                                            <span>
                                                {data && data.data && data.data.slot_date ? <>
                                                    {new Date(data.data.slot_date).toLocaleDateString('en-IN', { weekday: 'long' })}, {new Date(data.data.slot_date).getDate()} {new Date(data.data.slot_date).toLocaleDateString('en-IN', { month: 'long' })}, {new Date(data.data.slot_date).getFullYear()}
                                                </> : '-'}

                                            </span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>Time</th>
                                        <td>
                                            <span>{data.data && data.data.slot_time ? data.data.slot_time : '-'} </span>
                                        </td>
                                    </tr>

                                    <tr>
                                        <th>Status</th>
                                        <td>
                                            <span>
                                                {data.data.status === 1 ? "Requested" : data.data.status === 2 ? "Completed" : data.data.status === 3 ? "Cancelled" : 'Pending'}

                                            </span>
                                        </td>
                                    </tr>
                                    {data.data.status === 3 && <tr>
                                        <th>Cancel Reason</th>
                                        <td><span>{data.data.cancel_reason}</span></td>
                                    </tr>}
                                </table>


                                <h5 className="gap-top">Update Status</h5>
                                <form method='post' onSubmit={(e) => updateSellOrderStateAdmin(e)} id="admin-sell-request-order-form">
                                    <table>
                                        <tr>
                                            <th>Status</th>
                                            <td className="form-row">
                                                <select name="status" id="order-status" className="floating-select" >
                                                    <option value="1" selected={data.data.status === 1 ? true : false} >Requested</option>
                                                    <option value="2" selected={data.data.status === 2 ? true : false}>Completed</option>
                                                    <option value="3" selected={data.data.status == 3 ? true : false}>Cancelled</option>
                                                    <option value="5" selected={data.data.status === 5 ? true : false}>Pending</option>
                                                </select>
                                            </td>
                                        </tr>

                                        <tr>
                                            <th>Description</th>
                                            <td>
                                                <textarea name="cancel_reason" id="" rows="10">{data.data.cancel_reason}</textarea>
                                            </td>
                                        </tr>

                                        <tr>
                                            <th></th>
                                            <td className="common-buttons">
                                                <button className="green arrow-style">Update</button>
                                            </td>
                                        </tr>

                                    </table>
                                    <input type="hidden" name="id" defaultValue={Id} />
                                </form>
                            </div>
                        </div>

                    </div>
                </div >
            </Layout>
        </>
    )
}
