import React from 'react'
import Head from 'next/head'
import Layout from '@/components/common/Layout'
import Breadcrumb from '@/components/common/Breadcrumb'
import axios from 'axios'
import useSWR from 'swr';
import { convertTimeStamp, dateFormat } from '@/components/Helper'
import Link from 'next/link'
import Pagination from '@/components/common/Pagination';
import { useRouter } from 'next/router'

const fetcher = (url) => axios.get(url, { headers: { token: `${localStorage.getItem("lr-admin-token")}` } }).then(res => res.data)
export default function Index() {

    const router = useRouter()
    const { page } = router.query;
    const { data, error } = useSWR(`${process.env.NEXT_PUBLIC_URL}admin/sell-data-list?page=${page}`, fetcher);
    if (error) return 'Opps something went wrong'
    if (!data) return 'Please wait ...'

    return (
        <>
            <Head>
                <title>LR | Sell Data</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title="Sell Data" />
                <div className="main-data">

                    <div className="filters">

                        <div className="wrapper">

                            <div className="search common-div">

                                <input type="text" placeholder="Search here" />
                                <button></button>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Brands</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Type</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Status</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select button-style common-div">

                                <button>Apply Filters</button>

                            </div>

                            <div className="custom-select button-style common-div">

                                <button className="border-style">Clear Filters</button>

                            </div>

                        </div>

                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style={{ width: '100px', textAlign: 'center' }}>ID</th>
                                <th>UserName</th>
                                <th>Mobile No.</th>
                                <th>Brand</th>
                                <th>Model</th>
                                <th>Variant</th>
                                <th>Year</th>
                                <th>Kms</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Update At</th>
                                <th style={{ width: '200px' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {data && <>
                                {data && data.sellData.map((data, i) => {
                                    const count = 0
                                    return (
                                        <tr key={i}>
                                            <td>
                                                {i + 1}
                                            </td>
                                            <td>
                                                {data.user_name}
                                            </td>
                                            <td>
                                                {data.user_mobile}
                                            </td>
                                            <td>
                                                {data.brand_name && data.brand_name}
                                            </td>
                                            <td>
                                                {data.model_name && data.model_name}
                                            </td>
                                            <td>
                                                {data.variant_name && data.variant_name}
                                            </td>
                                            <td>
                                                {data.year}
                                            </td>
                                            <td>
                                                {data.kms}
                                            </td>

                                            <td>
                                                <button className={`small-btn ${data.status === 1 ? 'requested' : data.status === 2 ? 'active' : data.status === 3 ? 'cancelled' : 'pending'} `}>
                                                    {data.status === 1 ? 'Requested' : data.status === 2 ? 'Completed' : data.status === 3 ? 'Cancelled' : 'Pending'}
                                                </button>
                                            </td>
                                            <td>
                                                {convertTimeStamp(data.createdAt)}
                                            </td>
                                            <td>
                                                {convertTimeStamp(data.updatedAt)}
                                            </td>
                                            <td>
                                                <div className="table-buttons">

                                                    <Link href={`/admin/sell-data/${data.id}`}>
                                                        <button className='duplicate'>
                                                            View Detail
                                                        </button>
                                                    </Link>

                                                </div>
                                            </td>
                                        </tr>
                                    )
                                })}

                            </>}
                        </tbody>
                    </table>
                    <div>
                        <Pagination page={page} const rowCount={data !== undefined ? data.sellData : ''} />
                        {/* {console.log(countRow)} */}
                    </div>
                </div>
            </Layout>
        </>
    )
}
