import React from 'react'
import Head from 'next/head'
import Layout from '@/components/common/Layout'
import Breadcrumb from '@/components/common/Breadcrumb'
import axios from 'axios'
import useSWR from 'swr';
import { dateFormat } from '@/components/Helper'
import Link from 'next/link'
import Pagination from '@/components/common/Pagination';
import { useRouter } from 'next/router'
import { useState } from 'react'
import { useEffect } from 'react'

const fetcher = (url) => axios.get(url, { headers: { token: `${localStorage.getItem("lr-admin-token")}` } }).then(res => res.data)
export default function Index() {
    const router = useRouter()
    const { page } = router.query;
    const [data, setData] = useState([])
    const [filterData, setFilterData] = useState(data)

    const getAllSellData = async () => {
        await axios.get(`${process.env.NEXT_PUBLIC_URL}admin/sell-data-list?page=${page}`, {
            headers: {
                'token': localStorage.getItem('lr-admin-token'),
            }
        }).then((res) => {
            if (res && res.data && res.data.status === 1) {
                setData(res.data.sellData)
                setFilterData(res.data.sellData)
            }
        }).catch((e) => {
            if (e && e.message) {
                alert(e.message);
            } else if (e && e.response && e.response.data && e.response.data.status === 0) {
                alert(e.response.data.message);
            }
        })
    }
    const handleSearch = (event) => {
        let value = event.target.value;
        let result = [];
        console.log(value);
        result = data.filter((data) => {
            console.log(data.brand_name)
            return data.brand_name.search(value) != -1;
        });
        setFilterData(result);
    }


    useEffect(() => {
        getAllSellData()
    }, [page])

    // const { data, error } = useSWR(`${process.env.NEXT_PUBLIC_URL}admin/sell-data-list?page=${page}`, fetcher);
    // if (error) return 'Opps something went wrong'
    // if (!data) return 'Please wait ...'

    return (
        <>
            <Head>
                <title>LR | Sell Data</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title="Sell Data" />
                <div className="main-data">

                    <div className="filters">

                        <div className="wrapper">

                            <div className="search common-div">

                                <input type="text" placeholder="Search here" onChange={(event) => handleSearch(event)} />
                                <button></button>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Brands</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Type</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Status</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select button-style common-div">

                                <button>Apply Filters</button>

                            </div>

                            <div className="custom-select button-style common-div">

                                <button className="border-style">Clear Filters</button>

                            </div>

                        </div>

                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style={{ width: '100px', textAlign: 'center' }}>ID</th>
                                <th>UserName</th>
                                <th>Mobile No.</th>
                                <th>Brand</th>
                                <th>Model</th>
                                <th>Variant</th>
                                <th>Year</th>
                                <th>Kms</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Update At</th>
                                <th style={{ width: '200px' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {filterData && <>
                                {filterData && filterData.map((data, i) => {
                                    const count = 0
                                    return (
                                        <tr key={i}>
                                            <td>
                                                {i + 1}
                                            </td>
                                            <td>
                                                {data.user_name}
                                            </td>
                                            <td>
                                                {data.user_mobile}
                                            </td>
                                            <td>
                                                {data.brand_name && data.brand_name}
                                            </td>
                                            <td>
                                                {data.model_name && data.model_name}
                                            </td>
                                            <td>
                                                {data.variant_name && data.variant_name}
                                            </td>
                                            <td>
                                                {data.year}
                                            </td>
                                            <td>
                                                {data.kms}
                                            </td>

                                            <td>
                                                <button className={`small-btn ${data.status === 1 ? 'requested' : data.status === 2 ? 'active' : data.status === 3 ? 'cancelled' : 'pending'} `}>
                                                    {data.status === 1 ? 'Requested' : data.status === 2 ? 'Completed' : data.status === 3 ? 'Cancelled' : 'Pending'}
                                                </button>
                                            </td>
                                            <td>
                                                {dateFormat(data.createdAt)}
                                            </td>
                                            <td>
                                                {dateFormat(data.updatedAt)}
                                            </td>
                                            <td>
                                                <div className="table-buttons">
                                                    <button className='duplicate'>
                                                        <Link href={`/admin/sell-data/${data.id}`}>View Detail</Link>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                    )
                                })}

                            </>}
                        </tbody>
                    </table>
                    <div>
                        <Pagination page={page} const rowCount={data !== undefined ? data.sellData : ''} />
                        {/* {console.log(countRow)} */}
                    </div>
                </div>
            </Layout>
        </>
    )
}
