import Layout from '@/components/common/Layout'
import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Breadcrumb from '@/components/common/Breadcrumb'
import { ButtonSpinner, createSlug } from '@/components/Helper'
import axios from 'axios'
import { useRouter } from 'next/router'


export default function Index() {

    const [tinyloader, setTinyloader] = useState(false)
    const [formData, setFormData] = useState('')
    const router = useRouter()
    const [data, setData] = useState('')
    const query = router.query.id

    const eventChangeHandler = (e) => {
        setFormData((prevState) => ({
            ...prevState,
            [e.target.name]: e.target.value
        }));
    }

    const addUpdateBlogCategory = async (e) => {
        e.preventDefault();
        var createError = 0;

        if (e.target.name.value.length <= 0) {
            document.getElementById('blogNameError').innerHTML = 'Please enter name!';
            document.getElementById("blogNameError").style.display = "block";
            setTimeout(() => {
                document.getElementById('blogNameError').innerHTML = '';
                document.getElementById("blogNameError").style.display = "none";
            }, 3000);
            createError++;
        }

        if (e.target.slug.value.length <= 0) {
            document.getElementById('blogSlugError').innerHTML = 'Please enter slug!';
            document.getElementById("blogSlugError").style.display = "block";
            setTimeout(() => {
                document.getElementById('blogSlugError').innerHTML = '';
                document.getElementById("blogSlugError").style.display = "none";
            }, 3000);
            createError++;
        }

        if (createError > 0) {
            setTinyloader(false);
            return false;
        }
        setTinyloader(true);
        const addUrl = `${process.env.NEXT_PUBLIC_URL}admin/add-blog-category`
        const updateUrl = `${process.env.NEXT_PUBLIC_URL}admin/update-blog-category/${query}`

        if (query) {
            await axios.patch(updateUrl, formData, {
                headers: {
                    'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
                }
            }).then(function (res) {
                setTinyloader(false)
                if (res.data.status == 1) {
                    alert(res.data.message)
                    router.push('/admin/blog-category')
                }
            }).catch(function (error) {
                console.log(error)

            });
        } else {
            await axios.post(addUrl, formData, {
                headers: {
                    'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
                }
            }).then(function (res) {
                setTinyloader(false)
                if (res.data.status == 1) {
                    alert(res.data.message)
                    router.push('/admin/blog-category')
                }
            }).catch(function (error) {
                console.log(error)

            });
        }
    }


    const getBlogList = async () => {
        axios.get(`${process.env.NEXT_PUBLIC_URL}admin/view-blog-category?id=${query}`, {
            headers: {
                'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
            }
        }).then(function (res) {
            if (res.data.status == 1) {
                setData(res.data.data)
            }
        }).catch(function (error) {
            console.log(error)

        });
    }
    useEffect(() => {
        if (query) {
            getBlogList()
        }
    }, [query])



    return (
        <>
            <Head>
                <title>LR | {query ? 'Update' : 'Add'} Blog  Category </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title={query ? 'Update Blog  Category' : ' Add Blog  Category'} />
                <div className="form-style">
                    <form action="" id="blogCategoryForm" method='POST' onSubmit={(e) => addUpdateBlogCategory(e)}>
                        <div className="wrapper">
                            <div className="form-row">
                                <div className="form-div">
                                    <input type="hidden" name="id" value={data && data._id ? data._id : ''} />
                                    <input id="blogcategoryname" name='name' type="text" defaultValue={data && data.blog_category_name ? data.blog_category_name : ''} onChange={(e) => eventChangeHandler(e)} onKeyUp={(e) => createSlug(e.target.value, 'blogcategoryslug')} onLoad={() => createSlug(e.target.value, 'blogcategoryslug')} />
                                    <label htmlFor="blogcategoryname">Name</label>
                                    <small id="blogNameError" className="error"></small>
                                </div>
                                <div className="form-div">
                                    <input id="blogcategoryslug" name="slug" type="text" defaultValue={data && data.blog_category_slug ? data.blog_category_slug : ''} onChange={(e) => eventChangeHandler(e)} />
                                    <label htmlFor="blogcategoryslug">Slug</label>
                                    <small id="blogSlugError" className="error"></small>
                                </div>
                            </div>
                            <div className="common-buttons">
                                <button className="green" disabled={tinyloader}>
                                    <ButtonSpinner load={tinyloader} btnName="Save" />
                                </button>
                            </div>
                            <div>

                            </div>

                        </div>
                    </form>

                </div>
            </Layout>
        </>
    )
}