import Breadcrumb from '@/components/common/Breadcrumb'
import Layout from '@/components/common/Layout'
import Head from 'next/head'
import axios from 'axios'
import { dateFormat } from '@/components/Helper'
import Link from 'next/link'
import useSWR from 'swr';
import Paginationn from '@/components/common/Pagination'
import { useRouter } from 'next/router'


const fetcher = (url) => axios.get(url, { headers: { token: `${localStorage.getItem("lr-admin-token")}` } }).then(res => res.data)

export default function Index() {
    let router = useRouter()
    const { page } = router.query

    const { data, error } = useSWR(`${process.env.NEXT_PUBLIC_URL}admin/blog-list?page=${page}`, fetcher);

    if (error) return 'Opps something went wrong'
    if (!data) return 'Please wait ...'

    const updateStatus = async (status, id) => {
        await axios.get(`${process.env.NEXT_PUBLIC_URL}admin/update-blog-status?id=${id}&status=${status}`, {
            headers: {
                'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
            }
        }).then(function (res) {
            if (res.data.status == 1) {
                alert(res.data.message)
            }
        }).catch(function (error) {
            console.log(error)

        });
    }

    return (
        <>
            <Head>
                <title>LR | BLog Post   </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../../img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title="BLog Post" addBtn="Add BLog Post" url="/admin/blog-post/add-blog-post" />
                <div className="main-data">

                    <div className="filters">

                        <div className="wrapper">

                            <div className="search common-div">

                                <input type="text" placeholder="Search here" />
                                <button></button>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Brands</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Type</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Status</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select button-style common-div">

                                <button>Apply Filters</button>

                            </div>

                            <div className="custom-select button-style common-div">

                                <button className="border-style">Clear Filters</button>

                            </div>

                        </div>

                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style={{ width: '100px', textAlign: 'center' }}>ID</th>
                                <th style={{ width: '150px' }}>Image</th>
                                <th>Name</th>
                                <th>Slug</th>
                                <th>Category</th>
                                <th>Status</th>
                                <th>Short Description</th>
                                <th>Created At</th>
                                <th>Update At</th>
                                <th style={{ width: '200px' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {data && <>
                                {data.data.map((blog, i) => {
                                    return (
                                        <tr key={i}>
                                            <td>
                                                {i + 1}
                                            </td>
                                            <td> <img src={`${process.env.NEXT_PUBLIC_URL}public/blog-post/${blog.blog_image}`} style={{ height: '33px' }} /></td>
                                            <td>{blog.blog_name}</td>
                                            <td>{blog.blog_slug}</td>
                                            <td>{blog.blog_category_id && blog.blog_category_id.blog_category_name}</td>
                                            <td>
                                                <button className={`active small-btn ${blog.blog_status === 1 ? 'active' : 'inactive'} `} onClick={() => updateStatus(blog.blog_status === 1 ? 2 : 1, blog._id)}>{blog.blog_status === 1 ? 'active' : 'in-active'} </button>
                                            </td>
                                            <td>{blog.blog_short_description.substring(0, 60) + '...'}</td>
                                            <td>
                                                {dateFormat(blog.createdAt)}
                                            </td>
                                            <td> {dateFormat(blog.updatedAt)}</td>
                                            <td>
                                                <div className="table-buttons">
                                                    <Link href={`/admin/blog-post/add-blog-post?id=${blog._id}`}>
                                                        <button className='duplicate'>Edit</button>
                                                    </Link>
                                                </div>
                                            </td>
                                        </tr>
                                    )
                                })}
                            </>}
                        </tbody>
                    </table>
                    <div>
                        <Paginationn page={page} const rowCount={data !== undefined ? data.countBlogPosts : ''} />

                    </div>
                </div>
            </Layout>
        </>
    )
}
