import Layout from '@/components/common/Layout'
import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Breadcrumb from '@/components/common/Breadcrumb'
import { ButtonSpinner } from '@/components/Helper'
import axios from 'axios'
import { useRouter } from 'next/router'



export default function Index() {

    const [tinyloader, setTinyloader] = useState(false)
    const [formData, setFormData] = useState('')
    const router = useRouter()
    const [data, setData] = useState('')
    const query = router.query.id

    const eventChangeHandler = (e) => {
        setFormData((prevState) => ({
            ...prevState,
            [e.target.name]: e.target.value
        }));
    }

    const addUpdateFuelType = async (e) => {
        e.preventDefault();
        var createError = 0;

        if (e.target.name.value.length <= 0) {
            document.getElementById('colorNameError').innerHTML = 'Please enter name.';
            document.getElementById("colorNameError").style.display = "block";
            setTimeout(() => {
                document.getElementById('colorNameError').innerHTML = '';
                document.getElementById("colorNameError").style.display = "none";
            }, 3000);
            createError++;
        }

        if (e.target.color_code.value.length <= 0) {
            document.getElementById('colorCodeError').innerHTML = 'Please enter color code.';
            document.getElementById("colorCodeError").style.display = "block";
            setTimeout(() => {
                document.getElementById('colorCodeError').innerHTML = '';
                document.getElementById("colorCodeError").style.display = "none";
            }, 3000);
            createError++;
        }

        if (createError > 0) {
            setTinyloader(false);
            return false;
        }

        setTinyloader(true);
        const formData = new FormData(document.getElementById('colorForm'));
        const addUrl = `${process.env.NEXT_PUBLIC_URL}admin/add-color`
        const updateUrl = `${process.env.NEXT_PUBLIC_URL}admin/update-color/${query}`

        if (query) {
            console.log(formData)
            await axios.post(updateUrl, formData, {
                headers: {
                    'Content-Type': 'application/json',
                    'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
                }
            }).then(function (res) {
                setTinyloader(false)
                if (res.data.status == 1) {
                    router.push('/admin/color')
                }
            }).catch(function (error) {
                setTinyloader(false)
                console.log(error)

            });
        } else {
            formData.delete('id')
            await axios.post(addUrl, formData, {
                headers: {
                    'Content-Type': 'application/json',
                    'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
                }
            }).then(function (res) {
                setTinyloader(false)
                if (res.data.status == 1) {
                    alert(res.data.message);
                    router.push('/admin/color')
                }
            }).catch(function (error) {
                console.log(error)

            });
        }
    }


    const getColorView = async () => {
        axios.get(`${process.env.NEXT_PUBLIC_URL}admin/edit-color?id=${query}`, {
            headers: {
                'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
            }
        }).then(function (res) {
            if (res.data.status == 1) {
                setData(res.data.data)
            }
        }).catch(function (error) {
            console.log(error)

        });
    }
    useEffect(() => {
        if (query) {
            getColorView()
        }
    }, [query])

    return (
        <>
            <Head>
                <title>LR | {query ? 'Update' : 'Add'} Fuel Type </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title={query ? 'Update Fuel Type' : ' Add Fuel Type'} />
                <div className="form-style">
                    <form action="" id="colorForm" onSubmit={(e) => addUpdateFuelType(e)} method="POST">
                        <div className="wrapper">
                            <div className="form-row">
                                <div className="form-div">
                                    <input type="hidden" name="id" value={data && data._id ? data._id : ''} />
                                    <input id="colorname" name='name' placeholder=' ' type="text" defaultValue={data && data.name ? data.name : ''} />
                                    <label htmlFor="colorname">Color Name</label>
                                    <small id="colorNameError" className="error"></small>
                                </div>
                                <div className="form-div">
                                    <input id="colorCode" placeholder=' ' name="color_code" type="color" defaultValue={data && data.color_code ? data.color_code : ''} />
                                    <label htmlFor="colorCode">Color Code</label>
                                    <small id="colorCodeError" className="error"></small>
                                </div>
                                <div className="form-div">
                                    <input id="colorSorting" placeholder=' ' name="sorting" type="number" defaultValue={data && data.sorting ? data.sorting : ''} />
                                    <label htmlFor="colorSorting">Sorting</label>
                                    <small id="colorSorting" className="error"></small>
                                </div>
                            </div>
                            <div className="common-buttons">
                                <button className="green" disabled={tinyloader} type="submit">
                                    <ButtonSpinner load={tinyloader} btnName="Save" />
                                </button>
                            </div>
                            <div>

                            </div>

                        </div>

                    </form>
                </div>
            </Layout>
        </>
    )
}