import Breadcrumb from '@/components/common/Breadcrumb'
import Layout from '@/components/common/Layout'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import axios from 'axios'
import { dateFormat, fetchData } from '@/components/Helper'
import Link from 'next/link'
import useSWR from 'swr';
import { useRouter } from 'next/router'

const fetcher = (url) => axios.get(url, { headers: { token: `${localStorage.getItem("lr-admin-token")}` } }).then(res => res.data)

export default function Index() {

    const { data, error } = useSWR(`${process.env.NEXT_PUBLIC_URL}admin/color-list`, fetcher);

    if (error) return 'Opps something went wrong'
    if (!data) return 'Please wait ...'


    const deleteColor = async (id) => {
        await axios.get(`${process.env.NEXT_PUBLIC_URL}admin/delete-color/${id}`, {
            headers: {
                'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
            }
        }).then(function (res) {
            if (res.data.status == 1) {
                alert(res.data.message);
            }
        }).catch(function (error) {
            if (error.response.data.status === 0) {
                alert(err.response.data.message);
            }
        });
    }

    return (
        <>
            <Head>
                <title>LR | Colors</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../../img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title="Colors" addBtn="Add Color" url="/admin/color/add-color" />
                <div className="main-data">

                    <div className="filters">

                        <div className="wrapper">

                            <div className="search common-div">

                                <input type="text" placeholder="Search here" />
                                <button></button>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Brands</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Type</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Status</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select button-style common-div">

                                <button>Apply Filters</button>

                            </div>

                            <div className="custom-select button-style common-div">

                                <button className="border-style">Clear Filters</button>

                            </div>

                        </div>

                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style={{ width: '100px', textAlign: 'center' }}>ID</th>

                                <th>Color Name</th>
                                <th>Color Code</th>
                                <th>Sorting</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Update At</th>
                                <th style={{ width: '200px' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {data && data.data.length > 0 ? <>
                                {
                                    data.data.map((color, i) => {
                                        return (
                                            <tr key={i}>
                                                <td>
                                                    {i + 1}
                                                </td>

                                                <td>
                                                    {color.name}
                                                </td>
                                                <td>
                                                    {color.color_code}
                                                </td>
                                                <td>
                                                    {color.sorting}
                                                </td>
                                                <td>
                                                    <button className={`active small-btn ${color.status === 1 ? 'active' : 'inactive'} `} >{color.status === 1 ? 'active' : 'in-active'} </button>
                                                </td>
                                                <td>
                                                    {dateFormat(color.createdAt)}
                                                </td>
                                                <td>
                                                    {dateFormat(color.updatedAt)}
                                                </td>
                                                <td>
                                                    <div className="table-buttons">
                                                        <Link href={`/admin/color/add-color?id=${color._id}`}> <button className='duplicate'>Edit</button></Link>

                                                        <button class="serive" onClick={() => deleteColor(color._id)}>Delete</button>
                                                    </div>
                                                </td>
                                            </tr>
                                        )
                                    })
                                }

                            </> :
                                <tr >
                                    <td colSpan={7}>Data not Avaiable</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </Layout >
        </>
    )
} 