import React from 'react'
import Head from 'next/head'
import Layout from '@/components/common/Layout'
import Breadcrumb from '@/components/common/Breadcrumb'

export default function Index() {
    return (
        <>
            <Head>
                <title>LR | Newsletter Data</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title="Newsletter Data" />
                <div className="main-data">
                    <h2 style={{ textAlign: 'center' }}>In Progress...</h2>
                </div>
            </Layout>
        </>
    )
}
