import React from 'react'
import Head from 'next/head'
import Layout from '@/components/common/Layout'
import Breadcrumb from '@/components/common/Breadcrumb'
import axios from 'axios'
import useSWR from 'swr';
import { convertTimeStamp, dateFormat } from '@/components/Helper'
import Link from 'next/link'
import Pagination from '@/components/common/Pagination';
import { useRouter } from 'next/router'

const fetcher = (url) => axios.get(url, { headers: { token: `${localStorage.getItem("lr-admin-token")}` } }).then(res => res.data)
export default function Index() {

    const router = useRouter()
    const { page } = router.query;
    const { data, error } = useSWR(`${process.env.NEXT_PUBLIC_URL}admin/user-service-list?page=${page}`, fetcher);
    if (error) return 'Opps something went wrong'
    if (!data) return 'Please wait ...'

    const updateStatus = async (status, id) => {
        // let text = 'Are you sure you want update status?'

        // if (confirm(text) == true) {
        // await axios.get(`${process.env.NEXT_PUBLIC_URL}admin/block-unblock-experience-center?id=${id}&status=${status}`, {
        //     headers: {
        //         'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
        //     }
        // }).then(function (res) {
        //     if (res.data.status == 1) {
        //         alert(res.data.message);
        //     }
        // }).catch(function (error) {
        //     if (error.response.data.status === 0) {
        //         alert(err.response.data.message);
        //     }
        // });
        // }

    }

    return (
        <>
            <Head>
                <title>LR | Service</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title="Service Data" />
                <div className="main-data">

                    <div className="filters">

                        <div className="wrapper">

                            <div className="search common-div">

                                <input type="text" placeholder="Search here" />
                                <button></button>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Brands</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Type</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Status</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select button-style common-div">

                                <button>Apply Filters</button>

                            </div>

                            <div className="custom-select button-style common-div">

                                <button className="border-style">Clear Filters</button>

                            </div>

                        </div>

                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style={{ width: '100px', textAlign: 'center' }}>ID</th>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Mobile No.</th>
                                <th>Brand</th>
                                <th>Model</th>
                                <th>Variant</th>
                                <th>Fuel Type</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Update At</th>
                                <th style={{ width: '200px' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {data && <>
                                {data && data.data.map((data, i) => {
                                    const count = 0
                                    return (
                                        <tr key={i}>
                                            <td>
                                                {i + 1}
                                            </td>
                                            <td>
                                                {data.first_name ? data.first_name : '-'}
                                            </td>
                                            <td>
                                                {data.last_name ? data.last_name : '-'}
                                            </td>
                                            <td>
                                                {data.mobile}
                                            </td>
                                            <td>
                                                {data.brand_name}
                                            </td>
                                            <td>
                                                {data.model_name}
                                            </td>
                                            <td>
                                                {data.variant_name}
                                            </td>
                                            <td>
                                                {data.fuel_Type}
                                            </td>
                                            <td>
                                                <button className={`small-btn ${data.status === 1 ? 'requested' : data.status === 2 ? 'active' : data.status === 3 ? 'cancelled' : 'pending'} `}>
                                                    {data.status === 1 ? 'UpComing' : data.status === 2 ? 'Completed' : data.status === 3 ? 'Cancelled' : 'Pending'}
                                                </button>
                                            </td>
                                            <td>
                                                {convertTimeStamp(data.createdAt)}
                                            </td>
                                            <td>
                                                {convertTimeStamp(data.updatedAt)}
                                            </td>
                                            <td>
                                                <div className="table-buttons">
                                                    <Link href={`/admin/service/user-service-lead/${data._id}`}>
                                                        <button className='duplicate'>View Detail</button>
                                                    </Link>
                                                </div>
                                            </td>
                                        </tr>
                                    )
                                })}

                            </>}
                        </tbody>
                    </table>
                    <div>
                        <Pagination page={page} const rowCount={data !== undefined ? data.sellData : ''} />
                    </div>
                </div>
            </Layout>
        </>
    )
}
