import Head from "next/head"

function AdminHead({ pageTitle }) {
    return (
        <>
            <Head>
                <title> {pageTitle} | Luxury Ride </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link
                    href="/img/lr-favicon.ico"
                    rel="icon"
                    media="(prefers-color-scheme: light)"
                />
                <link
                    href="/img/lr-favicon-dark.ico"
                    rel="icon"
                    media="(prefers-color-scheme: dark)"
                />
            </Head>
        </>
    )
}

export default AdminHead