import Breadcrumb from '@/components/common/Breadcrumb'
import Layout from '@/components/common/Layout'
import Head from 'next/head'
import axios from 'axios'
import { dateFormat } from '@/components/Helper'
import Link from 'next/link'
import useSWR from 'swr';
import { useEffect, useState } from 'react'
import Paginationn from '@/components/common/Pagination'
import { useRouter } from 'next/router'


const fetcher = (url) => axios.get(url, { headers: { token: `${localStorage.getItem("lr-admin-token")}` } }).then(res => res.data)

export default function Index() {
    let router = useRouter()
    const { page } = router.query;
    const [datas, setData] = useState()
    const [countData, setCountData] = useState()



    const updateStatus = async (status, id) => {
        // axios.get(`${process.env.NEXT_PUBLIC_URL}admin/update-body-type-status?id=${id}&status=${status}`, {
        //     headers: {
        //         'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
        //     }
        // }).then(function (res) {
        //     if (res.data.status == 1) {
        //         alert(res.data.message)
        //     }
        // }).catch(function (error) {
        //     console.log(error)

        // });
    }

    const allNewsMediaList = async () => {
        axios.get(`${process.env.NEXT_PUBLIC_URL}admin/all-news-media?page=${page}`, {
            headers: {
                'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
            }
        }).then(function (res) {
            if (res.data.status == 1) {
                setData(res.data.data)
                setCountData(res.data.countNewsMedia)
            }
        }).catch(function (error) {
            console.log(error)

        });
    }

    useEffect(() => {
        import("react-datepicker/dist/react-datepicker.css");
        allNewsMediaList()
    }, [])

    const { data, error } = useSWR(`${process.env.NEXT_PUBLIC_URL}admin/all-news-media?page=${page}`, fetcher);

    if (error) return 'Opps something went wrong'
    if (!data) return 'Please wait ...'

    return (
        <>
            <Head>
                <title>LR | News and Media</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../../img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title="News Media" addBtn="Add News Media" url="/admin/news-media/add-news-media" />
                <div className="main-data">

                    <div className="filters">

                        <div className="wrapper">

                            <div className="search common-div">

                                <input type="text" placeholder="Search here" />
                                <button></button>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Brands</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Type</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Status</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select button-style common-div">

                                <button>Apply Filters</button>

                            </div>

                            <div className="custom-select button-style common-div">

                                <button className="border-style">Clear Filters</button>

                            </div>

                        </div>

                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style={{ width: '100px', textAlign: 'center' }}>ID</th>
                                <th style={{ width: '150px' }}>Image</th>
                                <th>Title</th>
                                <th>Slug</th>
                                <th>Short Description</th>
                                <th>Posted Date</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Update At</th>
                                <th style={{ width: '200px' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {data != undefined && data.data != undefined && data.data != '' ? <>
                                {data && data.data.map((newsmedia, i) => {
                                    return (
                                        <tr key={i}>
                                            <td>  {i + 1} </td>
                                            <td>
                                                <img src={`${process.env.NEXT_PUBLIC_URL}${newsmedia.image}`} width={70} />
                                            </td>
                                            <td> {newsmedia.title} </td>
                                            <td><Link href={`#`}>{newsmedia.slug}</Link></td>
                                            <td> {newsmedia.short_description.substring(0, 60) + '...'} </td>
                                            <td> {newsmedia.posted_date} </td>
                                            <td>
                                                <button className={`active small-btn ${newsmedia.status === 1 ? 'active' : 'inactive'} `} onClick={() => updateStatus(newsmedia.status === 1 ? 2 : 1, newsmedia._id)}>{newsmedia.status === 1 ? 'active' : 'in-active'} </button>
                                            </td>
                                            <td> {dateFormat(newsmedia.createdAt)} </td>
                                            <td> {dateFormat(newsmedia.updatedAt)} </td>
                                            <td>
                                                <div className="table-buttons">
                                                    <Link href={`/admin/news-media/add-news-media?id=${newsmedia._id}`}> <button className='duplicate'>Edit</button></Link>
                                                </div>
                                            </td>
                                        </tr>
                                    )
                                })}
                            </> : ''}
                        </tbody>
                    </table>
                    <div>
                        <Paginationn page={page} const rowCount={data ? data.countNewsMedia : ''} />

                    </div>
                </div>
            </Layout>
        </>
    )
}