import Breadcrumb from '@/components/common/Breadcrumb'
import Layout from '@/components/common/Layout'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import axios from 'axios'
import { dateFormat, fetchData } from '@/components/Helper'
import Link from 'next/link'
import useSWR from 'swr';
import { useRouter } from 'next/router'

const fetcher = (url, token) => axios.get(url, { headers: { token: `${localStorage.getItem("lr-admin-token")}` } }).then(res => res.data)

export default function Index() {

    const { data, error } = useSWR(`${process.env.NEXT_PUBLIC_URL}admin/fuel-list`, fetcher);

    if (error) return 'Opps something went wrong'
    if (!data) return 'Please wait ...'

    const updateStatus = async (status, id) => {
        // let text = 'Are you sure you want update status?'

        // if (confirm(text) == true) {
        await axios.get(`${process.env.NEXT_PUBLIC_URL}admin/update-fuel-status?id=${id}&status=${status}`, {
            headers: {
                'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
            }
        }).then(function (res) {
            if (res.data.status == 1) {
                alert(res.data.message);
            }
        }).catch(function (error) {
            if (error.response.data.status === 0) {
                alert(err.response.data.message);
            }
        });
        // }

    }

    return (
        <>
            <Head>
                <title>LR | Fuel Type   </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../../img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title="Fuel Type" addBtn="Add Fuel Type" url="/admin/fuel-type/add-fuel" />
                <div className="main-data">

                    <div className="filters">

                        <div className="wrapper">

                            <div className="search common-div">

                                <input type="text" placeholder="Search here" />
                                <button></button>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Brands</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Type</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Status</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select button-style common-div">

                                <button>Apply Filters</button>

                            </div>

                            <div className="custom-select button-style common-div">

                                <button className="border-style">Clear Filters</button>

                            </div>

                        </div>

                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style={{ width: '100px', textAlign: 'center' }}>ID</th>
                                <th style={{ width: '150px' }}>Image</th>
                                <th>Name</th>
                                <th>Slug</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Update At</th>
                                <th style={{ width: '200px' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {data && <>
                                {data.data.map((fuel, i) => {
                                    const count = 0
                                    return (
                                        <tr key={i}>
                                            <td>
                                                {i + 1}
                                            </td>
                                            <td>
                                                <img src={`${process.env.NEXT_PUBLIC_URL}${fuel.fuel_image}`} width={70} />
                                            </td>
                                            <td>
                                                {fuel.fuel_name}
                                            </td>
                                            <td>
                                                {fuel.fuel_slug}
                                            </td>
                                            <td>
                                                <button className={`active small-btn ${fuel.fuel_status === 1 ? 'active' : 'inactive'} `} onClick={() => updateStatus(fuel.fuel_status === 1 ? 2 : 1, fuel._id)}>{fuel.fuel_status === 1 ? 'active' : 'in-active'} </button>
                                            </td>
                                            <td>
                                                {dateFormat(fuel.createdAt)}
                                            </td>
                                            <td>
                                                {dateFormat(fuel.updatedAt)}
                                            </td>
                                            <td>
                                                <div className="table-buttons">
                                                    <Link href={`/admin/fuel-type/add-fuel?id=${fuel._id}`}> <button className='duplicate'>Edit</button>
                                                    </Link>
                                                </div>
                                            </td>
                                        </tr>
                                    )
                                })}

                            </>}
                        </tbody>
                    </table>
                </div>
            </Layout>
        </>
    )
} 