import Breadcrumb from '@/components/common/Breadcrumb'
import Layout from '@/components/common/Layout'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import axios from 'axios'
import { convertTimeStamp, dateFormat } from '@/components/Helper'
import Link from 'next/link'
import useSWR from 'swr';
import { useRouter } from 'next/router'
import Paginationn from '@/components/common/Pagination'

export default function Index() {

    const router = useRouter()
    const [service, setService] = useState([])
    const [serviceCat, setServiceCate] = useState('')
    const { page } = router.query;
    const serviceList = async () => {
        await axios.get(`${process.env.NEXT_PUBLIC_URL}admin/service-discount-list`, {
            headers: {
                'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
            }
        }).then(function (res) {
            if (res.data.status == 1) {
                setService(res.data.data)
                setServiceCate(res.data.data1)
            }
        }).catch(function (error) {
            if (error.response.data.status === 0) {
                alert(error.response.data.message);
            }
        });
    }

    const updateStatus = async (status, id) => {

        await axios.get(`${process.env.NEXT_PUBLIC_URL}admin/active-deactive-service-category?id=${id}&status=${status}`, {
            headers: {
                'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
            }
        }).then(function (res) {
            if (res.data.status == 1) {
                console.log(res.data.data)
                setService(res.data.data)
                alert(res.data.message);
            }
        }).catch(function (error) {
            if (error.response.data.status === 0) {
                alert(error.response.data.message);
            }
        });
    }
    console.log(service)
    useEffect(() => {
        serviceList()
    }, [])

    return (
        <>
            <Head>
                <title>LR | Service Discount</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link
                    href="/img/lr-favicon.ico"
                    rel="icon"
                    media="(prefers-color-scheme: light)"
                />
                <link
                    href="/img/lr-favicon-dark.ico"
                    rel="icon"
                    media="(prefers-color-scheme: dark)"
                />
            </Head>
            <Layout>
                <Breadcrumb title="Service Discount" addBtn="Add Service Discount" url="/admin/service/service-discount/add-service-discount" />
                <div className="main-data">

                    <div className="filters">

                        <div className="wrapper">

                            <div className="search common-div">

                                <input type="text" placeholder="Search here" />
                                <button></button>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Brands</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Type</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Status</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select button-style common-div">

                                <button>Apply Filters</button>

                            </div>

                            <div className="custom-select button-style common-div">

                                <button className="border-style">Clear Filters</button>

                            </div>

                        </div>

                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style={{ width: '100px', textAlign: 'center' }}>ID</th>
                                <th>Service Category</th>
                                <th>Name</th>
                                <th>Discount</th>
                                <th>Status</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th style={{ width: '200px' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {service != '' && service.length > 0 && service?.map((services, i) => {
                                const count = 0
                                return (
                                    <>
                                        {/* {services.service_sub_category != null ? */}
                                        <tr key={i}>
                                            <td>
                                                {i + 1}
                                            </td>
                                            <td>
                                                {services.service_category && services.service_category.service_category_name}
                                            </td>
                                            <td>
                                                {services.service_sub_category && services.service_sub_category.service_sub_category_name}
                                            </td>
                                            <td>
                                                {services.service_discount_price} {services.discount_type === '1' ? '₹' : '%'}
                                            </td>

                                            <td>
                                                {/* <button className={`active small-btn ${services.status === 1 ? 'active' : 'inactive'} `} onClick={() => updateStatus(services.status === 1 ? 2 : 1, services._id)}>{services.status === 1 ? 'active' : 'in-active'} </button> */}
                                                <button className={`active small-btn ${services.status === 1 ? 'active' : 'inactive'} `}>{services.status === 1 ? 'active' : 'in-active'} </button>
                                            </td>
                                            <td>
                                                {services.start_discount_date ? new Date(services.start_discount_date).toDateString() : ''}
                                            </td>
                                            <td>
                                                {services.end_discount_date ? new Date(services.end_discount_date).toDateString() : ''}
                                            </td>
                                            <td>
                                                <div className="table-buttons">
                                                    <Link href={`/admin/service/service-discount/add-service-discount?id=${services._id}`}>  <button className='duplicate'>Edit</button>
                                                    </Link>
                                                </div>
                                            </td>
                                        </tr>

                                        {/* : ''} */}

                                        {/* {serviceCat && serviceCat.map((subCat, i) => {
                                            return (
                                                <tr key={i}>
                                                    <td>
                                                        {i + 1}
                                                    </td>
                                                    <td>
                                                        {subCat.service_category && subCat.service_category.service_category_name}
                                                    </td>
                                                    <td>
                                                        {subCat.service_name}
                                                    </td>
                                                    <td>
                                                        {subCat.service_discount_price} {subCat.discount_type === '1' ? '₹' : '%'}
                                                    </td>

                                                    <td>
                                                        <button className={`active small-btn ${subCat.status === 1 ? 'active' : 'inactive'} `} onClick={() => updateStatus(subCat.status === 1 ? 2 : 1, subCat._id)}>{subCat.status === 1 ? 'active' : 'in-active'} </button>
                                                    </td>
                                                    <td>
                                                        {subCat.start_discount_date ? new Date(subCat.start_discount_date).toDateString() : ''}
                                                    </td>
                                                    <td>
                                                        {subCat.end_discount_date ? new Date(subCat.end_discount_date).toDateString() : ''}
                                                    </td>
                                                    <td>
                                                        <div className="table-buttons">
                                                            <Link href={`/admin/service/add-service?id=${subCat._id}`}>  <button className='duplicate'>Edit</button>
                                                            </Link>
                                                        </div>
                                                    </td>
                                                </tr>
                                            )
                                        })
                                        } */}

                                    </>

                                )
                            })
                            }
                        </tbody>
                    </table>
                    {/* <div>
                        <Paginationn page={page} const rowCount={service !== undefined ? service : ''} />
                      
                    </div> */}
                </div>
            </Layout>
        </>
    )
} 