import Breadcrumb from '@/components/common/Breadcrumb'
import Layout from '@/components/common/Layout'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import axios from 'axios'
import { dateFormat } from '@/components/Helper'
import Link from 'next/link'
import useSWR from 'swr';
import { useRouter } from 'next/router'

const fetcher = (url) => axios.get(url, { headers: { token: `${localStorage.getItem("lr-admin-token")}` } }).then(res => res.data)

export default function Index({ typeLayout }) {
    const router = useRouter()
    // const [data, setData] = useState('')

    const { data, error } = useSWR(`${process.env.NEXT_PUBLIC_URL}admin/blog-category-list`, fetcher);

    if (error) return 'Opps something went wrong'
    if (!data) return 'Please wait ...'


    const updateStatus = async (status, id) => {
        let statusValue = ''

        await axios.get(`${process.env.NEXT_PUBLIC_URL}admin/update-status?id=${id}&status=${status}`, {
            headers: {
                'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
            }
        }).then(function (res) {
            if (res.data.status == 1) {
                alert(res.data.message)
                router.push('/admin/blog-category')
            }
        }).catch(function (error) {
            console.log(error)

        });
    }


    // useEffect(() => {
    //     axios.get(`${process.env.NEXT_PUBLIC_URL}admin/blog-category-list`, {
    //         headers: {
    //             'token': typeof window !== "undefined" ? localStorage.getItem("lr-admin-token") : false,
    //         }
    //     }).then(function (res) {
    //         if (res.data.status == 1) {
    //             setData(res.data.data)
    //         }
    //     }).catch(function (error) {
    //         console.log(error)

    //     });
    // }, [])
    return (
        <>
            <Head>
                <title>LR | BLog Category   </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../../img/favicon.ico" />
            </Head>
            <Layout>
                <Breadcrumb title="BLog Category" addBtn="Add BLog Category" url="/admin/blog-category/add-blog-category" />
                <div className="main-data">

                    <div className="filters">

                        <div className="wrapper">

                            <div className="search common-div">

                                <input type="text" placeholder="Search here" />
                                <button></button>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Brands</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Type</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <select>

                                    <option>Status</option>
                                    <option>Brands</option>

                                </select>

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select common-div">

                                <input className="calender-style" type="text" placeholder="dd/mm/yyyy" />

                            </div>

                            <div className="custom-select button-style common-div">

                                <button>Apply Filters</button>

                            </div>

                            <div className="custom-select button-style common-div">

                                <button className="border-style">Clear Filters</button>

                            </div>

                        </div>

                    </div>

                    <table>
                        <thead>
                            <tr>
                                <th style={{ width: '100px', textAlign: 'center' }}>ID</th>
                                <th>Name</th>
                                <th>Slug</th>
                                <th>Status</th>
                                <th>Created At</th>
                                <th>Update At</th>
                                <th style={{ width: '200px' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {data && <>
                                {data.data.map((blog, i) => {
                                    const count = 0
                                    return (
                                        <tr key={i}>
                                            <td>
                                                {i + 1}
                                            </td>
                                            <td>
                                                {blog.blog_category_name}
                                            </td>
                                            <td>
                                                {blog.blog_category_slug}
                                            </td>
                                            <td>
                                                <button className={`active small-btn ${blog.blog_category_status === 1 ? 'active' : 'inactive'} `} onClick={() => updateStatus(blog.blog_category_status === 1 ? 2 : 1, blog._id)}>{blog.blog_category_status === 1 ? 'active' : 'in-active'} </button>

                                            </td>
                                            <td>
                                                {dateFormat(blog.createdAt)}
                                            </td>
                                            <td>
                                                {dateFormat(blog.updatedAt)}
                                            </td>
                                            <td>
                                                <div className="table-buttons">
                                                    <Link href={`/admin/blog-category/add-blog-category?id=${blog._id}`}><button className='duplicate'>Edit</button>
                                                    </Link>

                                                </div>
                                            </td>
                                        </tr>
                                    )
                                })}

                            </>}
                        </tbody>
                    </table>
                </div>
            </Layout>
        </>
    )
}
export const getServerSideProps = async (ctx) => {
    return {
        props: {
            typeLayout: 'admin',
        },
    };
};